name: Deploy Infrastructure 

on:
  push:
    branches:
      - main

jobs:
  deploy_site:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      
    - name: Execute Terraform in Subdirectories
      run: |
        for dir in terraform/*; do
          if [ -d "$dir" ]; then
            cd $dir
            terraform init
            terraform fmt -check
            terraform validate
            terraform plan
            terraform apply -auto-approve
            cd - 
          fi
        done
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # - name: Sync S3
    #   uses: jakejarvis/s3-sync-action@master
    #   with:
    #     args: --acl public-read
    #   env:
    #     SOURCE_DIR: './githubactions/tf.tfstate'
    #     AWS_REGION: 'us-east-1'
    #     AWS_S3_BUCKET: 'kwasiday5statebucket'